# A docker-compose file that runs commands out of a known image
# A windows-env file is required to run on Windows.

version: "2"

services:
  aws:
    env_file: windows-env
    image: tim77/limbo-test
    entrypoint: [ "/usr/local/bin/aws" ]

  ecs-cli:
    env_file: windows-env
    image: tim77/limbo-test
    entrypoint: /usr/local/bin/ecs-cli
